// <auto-generated />
using System;
using Infra.UPX4.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.UPX4.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241115204313_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("Infra.UPX4.Domain.Entities.PontoDeAcessibilidadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("cordx")
                        .HasColumnType("REAL");

                    b.Property<double>("cordy")
                        .HasColumnType("REAL");

                    b.Property<string>("descricaopontodeacessibilidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idicone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idusuariocriador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PontosDeAcessibilidade");
                });

            modelBuilder.Entity("Infra.UPX4.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5381c117-ce81-4de6-bed2-4d251a7bf8e8"),
                            CreateAt = new DateTime(2024, 11, 15, 17, 43, 13, 825, DateTimeKind.Local).AddTicks(7380),
                            Email = "adm@mail.com",
                            Name = "Adm",
                            Password = "adm123",
                            UpdatedAt = new DateTime(2024, 11, 15, 17, 43, 13, 825, DateTimeKind.Local).AddTicks(7398)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
