// <auto-generated />
using System;
using Infra.UPX4.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.UPX4.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241116173543_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Infra.UPX4.Domain.Entities.PontoDeAcessibilidadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("cordx")
                        .HasColumnType("REAL");

                    b.Property<double>("cordy")
                        .HasColumnType("REAL");

                    b.Property<string>("descricaopontodeacessibilidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idicone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("idusuariocriador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PontosDeAcessibilidade");
                });

            modelBuilder.Entity("Infra.UPX4.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cd0fcd9-454b-46db-b9e3-ef39e4a872db"),
                            CreateAt = new DateTime(2024, 11, 16, 14, 35, 42, 31, DateTimeKind.Local).AddTicks(7022),
                            Email = "adm@mail.com",
                            Name = "Adm",
                            Password = "adm123",
                            UpdatedAt = new DateTime(2024, 11, 16, 14, 35, 42, 36, DateTimeKind.Local).AddTicks(4202)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
